# Generated by Django 4.0.1 on 2023-03-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_app', '0002_csv_alter_login_groups_alter_login_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='NumberRoom',
            field=models.IntegerField(),
        ),
    ]
